[project]

name = "cache_dit"
dynamic = ["version", "dependencies", "optional-dependencies"]
requires-python = ">=3.10"
authors = [{name = "vipshop.com"}]
description = "⚡️DBCache: A Training-free UNet-style Cache Acceleration for Diffusion Transformers"

[project.urls]

Repository = "https://github.com/vipshop/DBCache.git"

[build-system]

requires = ["setuptools>=64", "setuptools_scm>=8"]
# build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[tool.black]

line-length = 80
target-version = ["py310"]
